In [1]:
import numpy as np

# Creating arrays
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# Element-wise operations
print(x * 2)        # Output: array([2, 4, 6, 8])
print(x + 10)       # Output: array([11, 12, 13, 14])
print(x + y)        # Output: array([ 6,  8, 10, 12])
print(x * y)        # Output: array([ 5, 12, 21, 32])

# Applying a function to an array
def f(x):
    return 3*x**2 - 2*x + 7

print(f(x))         # Output: array([ 8, 15, 28, 47])

# Universal functions
print(np.sqrt(x))   # Output: array([1.        , 1.41421356, 1.73205081, 2.        ])
print(np.cos(x))    # Output: array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Creating a large 2D array
grid = np.zeros(shape=(10000, 10000), dtype=float)
grid += 10
print(np.sin(grid))  # Applies sin function to all elements

# Indexing and slicing
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[1])          # Output: array([5, 6, 7, 8])
print(a[:, 1])       # Output: array([ 2,  6, 10])
a[1:3, 1:3] += 10
print(a)             # Output: array([[ 1,  2,  3,  4], [ 5, 16, 17,  8], [ 9, 20, 21, 12]])

# Conditional assignment
print(np.where(a < 10, a, 10))  # Output: array([[ 1,  2,  3,  4], [ 5, 10, 10,  8], [ 9, 10, 10, 10]])

[2 4 6 8]
[11 12 13 14]
[ 6  8 10 12]
[ 5 12 21 32]
[ 8 15 28 47]
[1.         1.41421356 1.73205081 2.        ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[[-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 ...
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]
 [-0.54402111 -0.54402111 -0.54402111 ... -0.54402111 -0.54402111
  -0.54402111]]
[5 6 7 8]
[ 2  6 10]
[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]
[[ 1  2  3  4]
 [ 5 10 10  8]
 [ 9 10 10 10]]
