In [1]:
import numpy as np

# Create a matrix
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
print("Matrix m:\n", m)

# Transpose of the matrix
print("Transpose of m:\n", m.T)

# Inverse of the matrix
print("Inverse of m:\n", m.I)

Matrix m:
 [[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
Transpose of m:
 [[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
Inverse of m:
 [[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]


In [2]:
# Create a vector
v = np.matrix([[2], [3], [4]])
print("Vector v:\n", v)

# Matrix multiplication
result = m * v
print("Result of m * v:\n", result)

Vector v:
 [[2]
 [3]
 [4]]
Result of m * v:
 [[ 8]
 [32]
 [ 2]]


In [3]:
# Determinant of the matrix
det = np.linalg.det(m)
print("Determinant of m:", det)

# Eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(m)
print("Eigenvalues of m:", eigenvalues)

Determinant of m: -229.99999999999983
Eigenvalues of m: [-13.11474312   2.75956154   6.35518158]


In [4]:
# Solve for x in mx = v
x = np.linalg.solve(m, v)
print("Solution x:\n", x)

# Verify the solution
print("Verification (m * x):\n", m * x)

Solution x:
 [[0.96521739]
 [0.17391304]
 [0.46086957]]
Verification (m * x):
 [[2.]
 [3.]
 [4.]]
